           var opsvisibleColumnIndexes = [0];
            var opscolors = [];
            for (var i = 1; i < opscolumns.length; i++) {
                if (opscolumns[i].visible) {
                    opscolors.push(opscolumns[i].color);
                    opsvisibleColumnIndexes.push(i);
                } else {
                    opscolors.push(opscolumns[i].disabledColor);
                    opsvisibleColumnIndexes.push({
                        calc: nullFunc,
                        type: opscolumns[i].type,
                        label: opscolumns[i].label,
                    });
                }
            };
            opsdataView.setColumns(opsvisibleColumnIndexes);
            opschart.draw(opsdataView, {
                colors: opscolors,
                interpolateNulls: true,
                width: 1800,
                height: 500,
                tooltip: { isHtml: true, textStyle: { fontSize: 10 } },       
                legend: {
                    position: 'right',
                    maxLines: 16,
                    textStyle: {
                        fontSize: 10
                    }
                },
                chartArea: {
                    'width': '80%',
                    'height': '80%'
                },
                hAxis: {
                    textPosition: 'none'
                },
                vAxis: {
                    textStyle: {
                        fontSize: 8
                    },
                    title: 'IOPs'
                }
            });
            var mbsvisibleColumnIndexes = [0];
            var mbscolors = [];
            for (var i = 1; i < mbscolumns.length; i++) {
                if (mbscolumns[i].visible) {
                    mbscolors.push(mbscolumns[i].color);
                    mbsvisibleColumnIndexes.push(i);
                } else {
                    mbscolors.push(mbscolumns[i].disabledColor);
                    mbsvisibleColumnIndexes.push({
                        calc: nullFunc,
                        type: mbscolumns[i].type,
                        label: mbscolumns[i].label,
                    });
                }
            };
            mbsdataView.setColumns(mbsvisibleColumnIndexes);
            mbschart.draw(mbsdataView, {
                colors: mbscolors,
                interpolateNulls: true,
                width: 1800,
                height: 500,
                tooltip: { isHtml: true, textStyle: { fontSize: 10 } },       
                legend: {
                    position: 'none',
                    textStyle: {
                        fontSize: 8
                    }
                },
                chartArea: {
                    'width': '80%',
                    'height': '80%'
                },
                hAxis: {
                    title: 'Run number',
                    slantedText: true,
                    slantedTextAngle: 45,
                    textStyle: {
                        fontSize: 8
                    }
                },
                vAxis: {
                    textStyle: {
                        fontSize: 8
                    },
                    title: 'MBs'
                }
            });
        };
    </script>
</head>
<body>
    <div id="opschart"></div>
    <div id="mbschart"></div>
</body>
</html>
